Fix found file #34

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -21,13 +21,13 @@ jobs:
           nbSuccess=0
           echo "| Files | Résults |" >> $GITHUB_STEP_SUMMARY
           echo "|-------|---------|" >> $GITHUB_STEP_SUMMARY
-          find docker-compose.yml && let nbSuccess++ && echo "| docker-compose.yml | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| docker-compose.yml | FAIL |" >> $GITHUB_STEP_SUMMARY
+          find ./docker-compose.yml && let nbSuccess++ && echo "| docker-compose.yml | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| docker-compose.yml | FAIL |" >> $GITHUB_STEP_SUMMARY
           find Server/Dockerfile && let nbSuccess++ && echo "| Server/Dockerfile | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| Server/Dockerfile | FAIL |" >> $GITHUB_STEP_SUMMARY
-          find Web/Dockerfile && let nbSuccess++ echo "| Web/Dockerfile | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| Web/Dockerfile | FAIL |" >> $GITHUB_STEP_SUMMARY
-          find Application/Dockerfile && let nbSuccess++ echo "| Application/Dockerfile | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| Application/Dockerfile | FAIL |" >> $GITHUB_STEP_SUMMARY
+          find Web/Dockerfile && let nbSuccess++ && echo "| Web/Dockerfile | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| Web/Dockerfile | FAIL |" >> $GITHUB_STEP_SUMMARY
+          find Application/Dockerfile && let nbSuccess++ && echo "| Application/Dockerfile | PASS |" >> $GITHUB_STEP_SUMMARY || echo "| Application/Dockerfile | FAIL |" >> $GITHUB_STEP_SUMMARY
           if (($nbSuccess == nbTests))
           then
-            echo "All file ($nbTests) are found!"
+            echo "All file ($nbTests) are found!" >> $GITHUB_STEP_SUMMARY
           else
             echo "$nbSuccess/$nbTests are found. Check previous line on stdout to know which file is missing." >> $GITHUB_STEP_SUMMARY
           fi
